'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("YieldMap.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All chains loaded; loading bond descriptions.
        '''</summary>
        Friend ReadOnly Property All_chains_loaded() As String
            Get
                Return ResourceManager.GetString("All_chains_loaded", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_rotate_clockwise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_rotate_clockwise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bond data loaded, storing into DB.
        '''</summary>
        Friend ReadOnly Property BondDataLoaded() As String
            Get
                Return ResourceManager.GetString("BondDataLoaded", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property briefcase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("briefcase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart_line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart_line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChartBubbleLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChartBubbleLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clipboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status : Connecting to Eikon....
        '''</summary>
        Friend ReadOnly Property Connecting_to_Eikon() As String
            Get
                Return ResourceManager.GetString("Connecting_to_Eikon", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property control_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DatabaseLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DatabaseLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database updated successfully.
        '''</summary>
        Friend ReadOnly Property DatabaseUpdatedSuccessfully() As String
            Get
                Return ResourceManager.GetString("DatabaseUpdatedSuccessfully", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property DefaultZoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultZoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eyeglasses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eyeglasses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to update database.
        '''</summary>
        Friend ReadOnly Property FailedToUpdateDatabase() As String
            Get
                Return ResourceManager.GetString("FailedToUpdateDatabase", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property fit_to_size() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fit_to_size", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property generic_folder_alt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generic_folder_alt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property graph_edge_curved() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graph_edge_curved", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide description pane.
        '''</summary>
        Friend ReadOnly Property HideDescriptionPane() As String
            Get
                Return ResourceManager.GetString("HideDescriptionPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialization of EikonDesktopSDK Fail.
        '''</summary>
        Friend ReadOnly Property Init_Eikon_Fail() As String
            Get
                Return ResourceManager.GetString("Init_Eikon_Fail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialized successfully.
        '''</summary>
        Friend ReadOnly Property Initialized_successfully() As String
            Get
                Return ResourceManager.GetString("Initialized_successfully", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property JustTile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JustTile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Labels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Labels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property media_fast_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_fast_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property media_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property media_play_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_play_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property media_stop_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_stop_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N/A.
        '''</summary>
        Friend ReadOnly Property N_A() As String
            Get
                Return ResourceManager.GetString("N_A", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pencil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlugLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlugLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reinitialization of EikonDesktopSDK is forbidden.
        '''</summary>
        Friend ReadOnly Property Reinit_Eikon_forbidden() As String
            Get
                Return ResourceManager.GetString("Reinit_Eikon_forbidden", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SettingsLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingsLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show description pane.
        '''</summary>
        Friend ReadOnly Property ShowDescriptionPane() As String
            Get
                Return ResourceManager.GetString("ShowDescriptionPane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status : Connected to Eikon.
        '''</summary>
        Friend ReadOnly Property Status_Connected() As String
            Get
                Return ResourceManager.GetString("Status_Connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status : Disconnected from Eikon.
        '''</summary>
        Friend ReadOnly Property Status_Disconnected() As String
            Get
                Return ResourceManager.GetString("Status_Disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status : Eikon local mode.
        '''</summary>
        Friend ReadOnly Property Status_Local() As String
            Get
                Return ResourceManager.GetString("Status_Local", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status : Offline.
        '''</summary>
        Friend ReadOnly Property Status_Offline() As String
            Get
                Return ResourceManager.GetString("Status_Offline", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property table2_run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table2_run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table2_run_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table2_run_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_marked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_marked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TileHor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileHor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TileVer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TileVer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unhandled domain exception.
        '''</summary>
        Friend ReadOnly Property Unhandled_domain_exception() As String
            Get
                Return ResourceManager.GetString("Unhandled_domain_exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unhandled thread exception.
        '''</summary>
        Friend ReadOnly Property Unhandled_thread_exception() As String
            Get
                Return ResourceManager.GetString("Unhandled_thread_exception", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property UnPin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnPin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Yield_Map_Icon_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Yield_Map_Icon_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property zoom_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoom_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomPrev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomPrev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
